name: Test workflow for example 03

on:
  push:
    branches: [ main, issue-* ]

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: ./bin/build.sh

      - name: Run example 03
        run: |
          docker run --rm \
            --env GPG_PRIVATE_KEY="${{ secrets.GPG_PRIVATE_KEY }}" \
            --env PASSPHRASE="${{ secrets.PASSPHRASE }}" \
            --env MODE="workflow" \
            --env REPO_DIR="/app" \
            --volume "$(pwd):/app" \
            pygithub src/03_sign_commit_using_the_gitpython_package.py