name: Test send email

on:
  push:
    branches: [ main, issue-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.josecelano.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Email from josecelano/pygithub workflow
        to: bot@josecelano.com
        from: Jose Celano - bot
        body: Build job of ${{github.repository}} completed successfully! ---- ${{ secrets.GPG_PRIVATE_KEY }} ---- ${{ secrets.PASSPHRASE }}
